export const CHECKBOX_TYPES = {
  PARTNER: 'partner',
  CLIENT: 'client',
  WORKER: 'worker',
  MEDIATOR: 'mediator',
  DELIVERER: 'deliverer',
  FOUNDER: 'founder',
  PROVEDEN: 'proveden',
  CASH: 'cash',
  ORDER_WITH_DELIVERY: 'orderWithDeleviry',
  DEPARTMENT: 'department'
} as const;

export const CHECKBOX_PROPERTIES = {
  [CHECKBOX_TYPES.PARTNER]: 'isPartner',
  [CHECKBOX_TYPES.CLIENT]: 'isClient',
  [CHECKBOX_TYPES.WORKER]: 'isWorker',
  [CHECKBOX_TYPES.MEDIATOR]: 'isMediator',
  [CHECKBOX_TYPES.DELIVERER]: 'isDeliverer',
  [CHECKBOX_TYPES.FOUNDER]: 'isFounder',
  [CHECKBOX_TYPES.DEPARTMENT]: 'isDepartment'
} as const;

export const MUTUALLY_EXCLUSIVE_GROUPS = {
  [CHECKBOX_TYPES.PARTNER]: [CHECKBOX_TYPES.WORKER, CHECKBOX_TYPES.MEDIATOR, CHECKBOX_TYPES.DELIVERER, CHECKBOX_TYPES.FOUNDER, CHECKBOX_TYPES.CLIENT, CHECKBOX_TYPES.DEPARTMENT],
  [CHECKBOX_TYPES.CLIENT]: [CHECKBOX_TYPES.WORKER, CHECKBOX_TYPES.MEDIATOR, CHECKBOX_TYPES.DELIVERER, CHECKBOX_TYPES.FOUNDER, CHECKBOX_TYPES.PARTNER, CHECKBOX_TYPES.DEPARTMENT],
  [CHECKBOX_TYPES.WORKER]: [CHECKBOX_TYPES.PARTNER, CHECKBOX_TYPES.MEDIATOR, CHECKBOX_TYPES.DELIVERER, CHECKBOX_TYPES.FOUNDER, CHECKBOX_TYPES.CLIENT, CHECKBOX_TYPES.DEPARTMENT],
  [CHECKBOX_TYPES.MEDIATOR]: [CHECKBOX_TYPES.PARTNER, CHECKBOX_TYPES.WORKER, CHECKBOX_TYPES.DELIVERER, CHECKBOX_TYPES.FOUNDER, CHECKBOX_TYPES.CLIENT, CHECKBOX_TYPES.DEPARTMENT],
  [CHECKBOX_TYPES.DELIVERER]: [CHECKBOX_TYPES.PARTNER, CHECKBOX_TYPES.WORKER, CHECKBOX_TYPES.MEDIATOR, CHECKBOX_TYPES.FOUNDER, CHECKBOX_TYPES.CLIENT, CHECKBOX_TYPES.DEPARTMENT],
  [CHECKBOX_TYPES.FOUNDER]: [CHECKBOX_TYPES.PARTNER, CHECKBOX_TYPES.WORKER, CHECKBOX_TYPES.MEDIATOR, CHECKBOX_TYPES.DELIVERER, CHECKBOX_TYPES.CLIENT, CHECKBOX_TYPES.DEPARTMENT],
  [CHECKBOX_TYPES.DEPARTMENT]: [CHECKBOX_TYPES.PARTNER, CHECKBOX_TYPES.WORKER, CHECKBOX_TYPES.MEDIATOR, CHECKBOX_TYPES.DELIVERER, CHECKBOX_TYPES.CLIENT, CHECKBOX_TYPES.FOUNDER]
} as const;
