import { Schet } from "src/interfaces/report.interface";
import { outIncome } from "./outIncome";
import { TypeReference } from "src/interfaces/reference.interface";
import { OborotsService } from "src/oborots/oborots.service";
import { StocksService } from "src/stocks/stocks.service";
import { remain } from "./remain";

export const financial = async (
  data: any,
  startDate: number | null,
  endDate: number | null,
  stocksService: StocksService,
  oborotsService: OborotsService,
  enterpriseId?: number | null,
) => {
  const promises = [
    remain(
      data,
      startDate,
      endDate,
      TypeReference.STORAGES,
      "startBalans",
      "POSUM",
      stocksService,
      oborotsService,
      enterpriseId,
    ),
    outIncome(
      data,
      startDate,
      endDate,
      Schet.S67,
      Schet.S50,
      TypeReference.WORKERS,
      "outForZP",
      "out",
      false,
      oborotsService,
      enterpriseId,
    ),
    outIncome(
      data,
      startDate,
      endDate,
      Schet.S60,
      Schet.S50,
      TypeReference.PARTNERS,
      "outForSuppliers",
      "out",
      false,
      oborotsService,
      enterpriseId,
    ),
    outIncome(
      data,
      startDate,
      endDate,
      Schet.S41,
      Schet.S50,
      TypeReference.PARTNERS,
      "outForDepartments",
      "out",
      false,
      oborotsService,
      enterpriseId,
    ),
    outIncome(
      data,
      startDate,
      endDate,
      Schet.S66,
      Schet.S50,
      TypeReference.STORAGES,
      "outForFounders",
      "out",
      false,
      oborotsService,
      enterpriseId,
    ),
    outIncome(
      data,
      startDate,
      endDate,
      Schet.S20,
      Schet.S50,
      TypeReference.CHARGES,
      "outForCharges",
      "out",
      true,
      oborotsService,
      enterpriseId,
    ),
    outIncome(
      data,
      startDate,
      endDate,
      Schet.S50,
      Schet.S40,
      TypeReference.PARTNERS,
      "incomeFromClients",
      "income",
      false,
      oborotsService,
      enterpriseId,
    ),
    outIncome(
      data,
      startDate,
      endDate,
      Schet.S50,
      Schet.S41,
      TypeReference.PARTNERS,
      "incomeFromDepartments",
      "income",
      false,
      oborotsService,
      enterpriseId,
    ),
    remain(
      data,
      startDate,
      endDate,
      TypeReference.STORAGES,
      "endBalans",
      "KOSUM",
      stocksService,
      oborotsService,
      enterpriseId,
    ),
  ];

  const results = await Promise.all(promises);
  return results;
};
