import { defaultDocument, defaultReportOptions, defaultJournalCheckbox, defaultInterval } from './app.context.helpers.constants'
import { Maindata } from './app.context.interfaces'
import { Setting, SettingType } from '../interfaces/settings.interface'

export const defaultMainData: Maindata = {
    document: {
        currentDocument: {...defaultDocument},
        showDocumentWindow: false,
        isNewDocument: false,
        showMayda: false,
        contentType: 'document',
        contentName: '',
        contentTitle: '',
        comeProductCalculationSignature: null,
        isDuplicateDraft: false,
        keepHostPageOnClose: false,
    },
    reference: {
        currentReference: undefined,
        allReferences: undefined,
        showReferenceWindow: false,
        isNewReference: false,
        selectedEnterpriseId: null,
        inlineCreation: null,
        nestedInlineCreation: null,
        lastCreatedForInline: null,
    },
    pereodic: {
        currentPereodic: undefined,
        showPereodicWindow: false,
        isNewPereodic: false,
        showPereodicsListWindow: false,
        referenceIdForPereodicsList: -1,
        referenceNameForPereodicsList: '',
        valueNameForPereodicsList: '',
        valueNameTranslateForPereodicsList: '',
        updateDataForPereodicsList: false,
    },
    settings: {
        currentSetting: undefined,
        allSettings: undefined,
        singleEnterpriseMode: false,
        avtoProvodkaInManyEnterpriseMode: false,
        dateBanEditing: null,
    },
    settingPereodic: {
        currentSettingPereodic: undefined,
        showSettingPereodicWindow: false,
        isNewSettingPereodic: false,
        showSettingPereodicsListWindow: false,
        settingIdForPereodicsList: -1,
        settingKeyForPereodicsList: '',
        pereodicScopeEnterpriseId: null,
        updateDataForSettingPereodicsList: false,
    },
    report: {
        reportOption: {...defaultReportOptions},
        loading: false,
        informData: [],
        matOborot: [],
        osOborot: [],
        oborotka: [],
        personal: [],
        mediatorPersonal: [],
        delivererPersonal: [],
        clients: [],
        aktSverka: [],
        currentDKInnerReportId: -1,
        currentDKInnerArrayId: -1,
        dashboardCurrentReportType: '',
        dashboardReturnReportType: null,
        currentFinancialInnerReportType: 'outZP',
        showPereodicListWindow: false,
        selectedEnterpriseId: null,
    },
    journal: {
        updateDataForDocumentJournal: false,
        updateDataForUserJournal: false,
        journalChechboxs: defaultJournalCheckbox,
        updateDataForRefenceJournal: false,
        updateDataForSettingsJournal: false,
        updateDataForEnterpriseJournal: false,
        interval: defaultInterval,
        showIntervalWindow: false,
        activeTab: 'CASH' as 'CASH' | 'BANK' | 'USD' | 'PLASTIK',
        lastActedDocumentId: null,
        navigateToLastActedDocument: false,
    },
    window: {
        showMessageWindow: false,
        message: 'Маълумотлар сакланди',
        messageType: 'error',
        clearControlElements: false,
        showSettingsWindow: false,
        isNewSetting: false,
        activeMenuKey: '',
        mainPage: true,
        uploadingDashboard: false,
        showPaymentLessThanIncomeModal: false,
        rentalReadyOrders: null,
        showReadyRentalOrdersModal: false,
    },
    users: {
        user: undefined,
        currentUser: undefined,
        usersName: undefined,
        showUserWindow: false,
        isNewUser: false,
    },
    enterprises: {
        currentEnterprise: undefined,
        showEnterpriseWindow: false,
        isNewEnterprise: false,
    },
    enterpriseSettings: {
        menuVisibility: undefined,
    },
    platform: {
        info: undefined
    },
    minimizedWindows: [],
  }