ALTER TABLE docvalues ADD COLUMN IF NOT EXISTS "isDeliverer" BOOLEAN DEFAULT false;
ALTER TABLE docvalues ADD COLUMN IF NOT EXISTS "delivererId" INTEGER;
ALTER TABLE docvalues ADD COLUMN IF NOT EXISTS "deliverySum" FLOAT;
