ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "shortName" VARCHAR(255);
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "size" VARCHAR(255);
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "color" VARCHAR(255);
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "manufacture" VARCHAR(255);
