ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "isLegalEntity" BOOLEAN DEFAULT false;
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "bankName" VARCHAR(255);
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "bankAccount" VARCHAR(20);
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "bankMfo" VARCHAR(5);
