ALTER TABLE refvalues
  ADD COLUMN IF NOT EXISTS "tmzWorks" JSONB NULL,
  ADD COLUMN IF NOT EXISTS "tmzMaterials" JSONB NULL,
  ADD COLUMN IF NOT EXISTS "tmzTechMap" JSONB NULL,
  ADD COLUMN IF NOT EXISTS "tmzComponents" JSONB NULL,
  ADD COLUMN IF NOT EXISTS "tmzPricing" JSONB NULL,
  ADD COLUMN IF NOT EXISTS "filesFromScaling" JSONB NULL,
  ADD COLUMN IF NOT EXISTS "filesFromDrawing" JSONB NULL;
