ALTER TABLE order_works
    ADD COLUMN IF NOT EXISTS "countInUnit" FLOAT,
    ADD COLUMN IF NOT EXISTS "countInOrder" FLOAT,
    ADD COLUMN IF NOT EXISTS "timeInUnit" FLOAT,
    ADD COLUMN IF NOT EXISTS "timeInOrder" FLOAT,
    ADD COLUMN IF NOT EXISTS "salaryInUnit" FLOAT,
    ADD COLUMN IF NOT EXISTS "salaryInOrder" FLOAT,
    ADD COLUMN IF NOT EXISTS "class" VARCHAR(255);
