ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS phone2 VARCHAR(255);
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "contactName1" VARCHAR(255);
ALTER TABLE refvalues ADD COLUMN IF NOT EXISTS "contactName2" VARCHAR(255);
