export enum UserRoles {
  ADMINGLOBAL = "ADMINGLOBAL",
  HEADGLOBAL = "HEADGLOBAL",
  KASSIRGLOBAL = "KASSIRGLOBAL",

  HEADCOMPANY = "HEADCOMPANY",
  GLAVBUX = "GLAVBUX",

  GUEST = "GUEST",
  KASSIR = "KASSIR",
  ZAVSKLAD = "ZAVSKLAD",
  SCALING = "SCALING",
  DRAWING = "DRAWING",
  DELIVERY = "DELIVERY",
  MARKETING = "MARKETING",
  PRODUCTION = "PRODUCTION",
  TEXNOLOG = "TEXNOLOG",
}
