import { DocumentType } from "../../../../../interfaces/document.interface";

export const docsDependentToBalance = [
  `${DocumentType.SaleProd}`,
  `${DocumentType.SaleTovar}`,
  `${DocumentType.SaleMaterial}`,
  `${DocumentType.SaleOS}`,
  `${DocumentType.LeaveProd}`,
  `${DocumentType.LeaveOS}`,
  `${DocumentType.LeaveMaterial}`,
  `${DocumentType.LeaveTools}`,
  `${DocumentType.TransferToolsToClient}`,
  `${DocumentType.LeaveTovar}`,
  `${DocumentType.LeaveOnlyOneMaterial}`,
  `${DocumentType.LeaveHalfstuff}`,
  `${DocumentType.MoveProd}`,
  `${DocumentType.MoveMaterial}`,
  `${DocumentType.MoveTools}`,
  `${DocumentType.TransferToolsToClient}`,
  `${DocumentType.MoveOS}`,
  `${DocumentType.MoveHalfstuff}`,
  `${DocumentType.ComeHalfstuff}`,
]

export const docsDependentToMiddlePrice = [
  `${DocumentType.SaleMaterial}`,
  `${DocumentType.SaleOS}`,
  `${DocumentType.SaleTovar}`,
  `${DocumentType.LeaveMaterial}`,
  `${DocumentType.LeaveTools}`,
  `${DocumentType.TransferToolsToClient}`,
  `${DocumentType.LeaveTovar}`,
  `${DocumentType.LeaveOS}`,
  `${DocumentType.LeaveOnlyOneMaterial}`,
  `${DocumentType.LeaveHalfstuff}`,
  `${DocumentType.MoveMaterial}`,
  `${DocumentType.MoveTools}`,
  `${DocumentType.TransferToolsToClient}`,
  `${DocumentType.MoveOS}`,
  `${DocumentType.MoveHalfstuff}`,
  `${DocumentType.ComeHalfstuff}`,
  `${DocumentType.SaleHalfStuff}`,
]

export const docsNotDependentToTotal = [
  `${DocumentType.MoveProd}`,
]

export const allDocs = [
  `${DocumentType.ComeMaterial}`,
  `${DocumentType.ComeTools}`,
  `${DocumentType.TransferToolsToClient}`,
  `${DocumentType.ComeTovar}`,
  `${DocumentType.ComeOS}`,
  `${DocumentType.ComeProduct}`,
  `${DocumentType.ComeHalfstuff}`,
  `${DocumentType.SaleProd}`,
  `${DocumentType.SaleTovar}`,
  `${DocumentType.SaleMaterial}`,
  `${DocumentType.LeaveProd}`,
  `${DocumentType.LeaveMaterial}`,
  `${DocumentType.LeaveTools}`,
  `${DocumentType.TransferToolsToClient}`,
  `${DocumentType.LeaveTovar}`,
  `${DocumentType.LeaveOnlyOneMaterial}`,
  `${DocumentType.LeaveHalfstuff}`,
  `${DocumentType.MoveProd}`,
  `${DocumentType.MoveMaterial}`,
  `${DocumentType.MoveTools}`,
  `${DocumentType.TransferToolsToClient}`,
  `${DocumentType.MoveOS}`,
  `${DocumentType.MoveHalfstuff}`,
  `${DocumentType.LeaveOS}`,
  `${DocumentType.SaleOS}`,
  `${DocumentType.AmortizasiyaOS}`,
  `${DocumentType.ComeCashFromClients}`,
  `${DocumentType.MoveCash}`,
  `${DocumentType.LeaveCash}`,
  `${DocumentType.ZpCalculate}`,
]
