"use client";
import { Schet } from "src/interfaces/report.interface";
import { debitorKreditorInners } from "./debitorKreditorInners";
import { debitorKreditorOs } from "./debitorKreditorOs";
import { debitorKreditorToolsWarehouse } from "./debitorKreditorToolsWarehouse";
import { debitorKreditorToolsAtClient } from "./debitorKreditorToolsAtClient";
import { TypeReference } from "src/interfaces/reference.interface";
import { StocksService } from "src/stocks/stocks.service";
import { OborotsService } from "src/oborots/oborots.service";
import { ExchangeService } from "src/exchange/exchange.service";
import { DebitorKreditorMode } from "./debitorKreditorMode";

export const debitorKreditor = async (
  data: any,
  startDate: number | null,
  endDate: number | null,
  stocksService: StocksService,
  oborotsService: OborotsService,
  exchangeService?: ExchangeService,
  enterpriseId?: number | null,
  mode: DebitorKreditorMode = "balances",
) => {
  // console.time('DebitorKreditor');

  const tasks = [
    debitorKreditorOs(
      data,
      startDate,
      endDate,
      stocksService,
      oborotsService,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S10,
      TypeReference.TMZ,
      "MATERIAL",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S29,
      TypeReference.TMZ,
      "TOVAR",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    // debitorKreditorInners(data, startDate, endDate, Schet.S21, TypeReference.TMZ, 'ZAGATOVKA', stocksService, oborotsService, exchangeService, false, enterpriseId)
    //     .then(result => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S28,
      TypeReference.TMZ,
      "PRODUCTIONS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    // debitorKreditorInners(data, startDate, endDate, Schet.S50, TypeReference.STORAGES, 'FILIAL', stocksService, oborotsService, exchangeService, false, enterpriseId)
    //     .then(result => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S40,
      TypeReference.PARTNERS,
      "CLIENTS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S41,
      TypeReference.STORAGES,
      "DEPARTMENTS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S50,
      TypeReference.STORAGES,
      "BUXGALTER",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    // debitorKreditorInners(data, startDate, endDate, Schet.S50, TypeReference.STORAGES, 'DELIVERY', stocksService, oborotsService, exchangeService, false, enterpriseId)
    //     .then(result => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S60,
      TypeReference.PARTNERS,
      "SUPPLIERS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S66,
      TypeReference.STORAGES,
      "FOUNDERS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S67,
      TypeReference.WORKERS,
      "WORKERS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S65,
      TypeReference.PARTNERS,
      "MEDIATORS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorInners(
      data,
      startDate,
      endDate,
      Schet.S64,
      TypeReference.DELIVERERS,
      "DELIVERERS",
      stocksService,
      oborotsService,
      exchangeService,
      false,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorToolsWarehouse(
      data,
      startDate,
      endDate,
      stocksService,
      oborotsService,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
    debitorKreditorToolsAtClient(
      data,
      startDate,
      endDate,
      stocksService,
      oborotsService,
      enterpriseId,
      mode,
    ).then((result) => ({ ...result })),
  ];

  const result = await Promise.all(tasks);
  // console.timeEnd('DebitorKreditor');
  return result;
};
